# Generated by Django 3.1.7 on 2021-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendence',
            name='name',
            field=models.CharField(help_text='Enter your Name', max_length=1000),
        ),
    ]
