# Generated by Django 3.1.7 on 2021-03-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210329_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name', 'date_of_start']},
        ),
    ]
