# Generated by Django 3.1.7 on 2021-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210329_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendence',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
