# Generated by Django 3.1.7 on 2021-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210401_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendence',
            name='name',
            field=models.CharField(help_text='Enter your Name', max_length=1000),
        ),
    ]
